Test under Ruby 2.3 as fakefs requires it
Cannot run tests under Ruby 2.2 based on the following:

    $ gem install fakefs
    Fetching: fakefs-0.18.0.gem (100%)
    ERROR:  Error installing fakefs:
        fakefs requires Ruby version >= 2.3.0.